# Use the Visual Studio 2019 image
image: Visual Studio 2019

# Environment variables
environment:
  QTDIR: "C:\\Qt\\5.15.2\\msvc2019"
  PATH: "%QTDIR%\\bin;%PATH%"

# Build script
build_script:
  - mkdir ..\build
  - cd ..\build
  - qmake ..\CI-CD-App\CI-CD-App.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
  - nmake
  
  
