# Use the Visual Studio 2019 image
image: Visual Studio 2019

# Environment variables
environment:
  matrix:
    - arch: x86
      compiler: msvc2019
    - arch: x64
      compiler: msvc2019
  QTDIR: "C:\\Qt\\5.15.2\\msvc2019"
  VC2019: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.31.31103\\bin\\Hostx64\\x64"
  PATH: "%VC2019%;%QTDIR%\\bin;%PATH%"

platform:
  - x64
  
# Build script
build_script:
  - echo %PATH%
  - dir "C:\\"
  - where qmake
  - where cl.exe
  - where nmake
  - mkdir ..\build
  - cd ..\build
  - qmake ..\CI-CD-Public\CI-CD-App.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
  - nmake
  
  
